# Generated by Django 2.0.7 on 2018-07-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180718_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
